name: testdevops

on:
  push: 
    branches: 
      - '**'

env:
  REGISTRY_USER: ninotter
  DOCKERUP_PASSWORD: ${{secrets.DOCKERUP_PASSWORD}}
  
jobs:
  build_default_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [workspace,php-fpm,nginx]
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: copy-env
        run: cp .env.example .env

      - name: set-shortsha
        id: commit-sha
        run: echo "sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: prepare-docker-compose
        run: |
          SHA=${{steps.vars.output.sha}}
          sed -i "s~__WORKSPACE_IMAGE__~${REGISTRY_USER}/workspace_${SHA}~g" docker-compose.prod.yml
          sed -i "s~__PHP_FPM_IMAGE__~${REGISTRY_USER}/php_fpm_${SHA}~g" docker-compose.prod.yml
          sed -i "s~__NGINX_IMAGE__~${REGISTRY_USER}/nginx_${SHA}~g" docker-compose.prod.yml
      
      - name: docker-login
        run: echo "${DOCKERUP_PASSWORD}" | docker login -u ninotter --password-stdin

      - name: Enable Docker BuildKit
        run: |
          echo '{"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: docker-build ${{matrix.service}}
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build ${{matrix.service}}

      - name: docker-push ${{matrix.service}}
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml push ${{matrix.service}}
